### ISSUE TITLE
outdated README.md

### ISSUE THREAD

**Issue by at-the-vr** [sarah11918/astro-docs-docs#7]
The current README.md includes boilerplate from Starlight and some Sarah's points. Time to update it

## Why?
Why not 😆 since AD<sup>2</sup> is updated and covers everything, README can be clarified a bit more

**Comment by at-the-vr** [comment]
Before creating PR for this, I want to confirm with the structure for README for AD<sup>2</sup>

Here's a prototype in [HACKMD](https://hackmd.io/@at-the-vr/rJOuVxFta/edit)

**Comment by sarah11918** [comment]
@at-the-vr Sorry, I forget to check in on this repo! I should probably enable explicit notifications since it's such low-traffic.

I love your edit! Would be happy if you'd like to make a PR!
